---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk01-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disk01"