bases:
  - ./common/
  - ./team1/
  - ./dns/
  - ./dashboard/
  - ./flagger/
  - ./gatekeeper/
  - ./ingress/
  - ./metallb/
  - ./metrics/
  - ./registry/
  - ./sealed-secret/
  - ./storage/
  - ./extra/fluentd/