apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - rbac.yaml
  - psp.yaml
bases:
  - ../base/flux/
  - ../base/memcached/
patchesStrategicMerge:
  - flux-patch.yaml