apiVersion: v1
data:
  basic-auth-password: NDkyNDg3MDQ2ZTBhOWZjOGU5YjdlYjdkNjhiOWIzMjExOThmYTAzZQ==
  basic-auth-user: YWRtaW4=
kind: Secret
metadata:
  name: basic-auth
  namespace: open-faas
type: Opaque