apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
spec:
  template:
    spec:
      containers:
        - name: flagger
          image: olaffreund/flagger-arm64:arm
          imagePullPolicy: IfNotPresent
          args:
            - -mesh-provider=kubernetes
            - -metrics-server=http://flagger-prometheus:9090
            - -slack-user=flagger
            - -slack-channel=flagger
            - -slack-url=https://hooks.slack.com/services/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