namespace: flagger-system
resources:
  - namespace.yaml
bases:
  - github.com/olafkfreund/flagger/kustomize/base/flagger
  - github.com/weaveworks/flagger/kustomize/base/prometheus
patchesStrategicMerge:
  - flagger-patch.yaml