apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flagger-system
resources:
  - namespace.yaml
bases:
  - github.com/olafkfreund/flagger/kustomize/base/flagger
  - github.com/olafkfreund/flagger/kustomize/base/prometheus
patchesStrategicMerge:
  - flagger-patch.yaml