namespace: flagger-system
resources:
  - namespace.yaml
bases:
  - github.com/weaveworks/flagger/kustomize/base/flagger
  - ./extra/promethues/setup/
  - ./extra/promethues/
patchesStrategicMerge:
  - flagger-patch.yaml